[package]
name = "cairo-m-runner"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
cairo-m-common.workspace = true
cairo-m-runner.workspace = true
thiserror.workspace = true
sonic-rs.workspace = true
uniffi.workspace = true
