# .github/workflows/eas-build.yml
# Thank you to https://github.com/thomasread99/expo-workflows for the inspiration!

name: Local EAS Build PR Check

permissions:
  contents: read

# Add concurrency to cancel previous runs
concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name:
      ${{ matrix.platform == 'android' && 'Android' || 'iOS device' }} Local
      Build (Preview)
    runs-on: macos-15

    strategy:
      matrix:
        platform: [android, ios]
        include:
          - platform: android
            artifact-name: app-preview-android
            output-file: app-release.apk
            build-command:
              eas build --local --platform android --profile preview
              --non-interactive --output ${{ github.workspace }}/app-release.apk
            success-message: "✅ Android local build successful!"
          - platform: ios
            artifact-name: app-preview-ios
            output-file: app-release.ipa
            build-command:
              eas build --local --platform ios --profile preview
              --non-interactive --output ${{ github.workspace }}/app-release.ipa
            success-message: "✅ iOS (device) local build successful!"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup lld linker (iOS only)
        if: matrix.platform == 'ios'
        run: brew install lld

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run EAS Local Build (Preview Profile)
        run: ${{ matrix.build-command }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ github.workspace }}/${{ matrix.output-file }}

      - name: Indicate Build Success
        run: echo "${{ matrix.success-message }}"
